### ISSUE TITLE
How to deal with .mzid result file in target mode

### ISSUE THREAD

**Issue by ghost** [abdrakhimov1/Biosaur#22]
Hello!
I am trying to use the target mode in Biosaur, but the command line you provide 
"biosaur YOUR_FILE.mzML --pxfp YOUR_SEARCH_ENGINE_RESULT.pep.xml"
can't work when I change the last path of .xml file to .mzid file from MS-GF+.

I wonder if the command "--pxfp" should be something else...?
Thanks for your reply. : )

**Comment by markmipt** [comment]
Hi,

We have a completely rewritten version of Biosaur which is place here: https://github.com/markmipt/biosaur2 . It is faster, more efficient and has less bugs. The only thing is that biosaur2 has no built-in targeted mode. However, we have IQMMA tool (https://github.com/PostoenkoVI/IQMMA) which was developed to do some "sophisticated" targeted mode using up to three possible peptide feature detection methods (biosaur2, Dinosaur and OpenMS FeatureFinder). It supports MS-GF+ .mzid files out of the box (among pep.xml and some custom tsv formats).

Will it help you with your issue?

Regards,
Mark Ivanov

**Comment by ghost** [comment]
Hi Dr. Ivanov,
Thanks for your response! 
I notice that the IQMMA tool was just presented recently. I'll read your article and try the IQMMA tool to deal with my result. The function of enabling users to provide their results in .tsv table seens convenient and helpful. I'll try the .mzid result first and provide feedbacks in the issue page of IQMMA (https://github.com/PostoenkoVI/IQMMA). Thanks again!

Best wishes : )

**Comment by markmipt** [comment]
Thanks for the interest in our tools! Looking forward to your feedback and suggestions.
